import { defineAgent } from '@codebuff/sdk';

// 1. MASTER ORCHESTRATOR
export const masterOrchestrator = defineAgent({
  name: 'Orchestrator',
  description: 'Spawns dynamic specialized agents that command Freebuff functional primitives.',
  
  async workflow(ctx, massiveUserInput) {
    ctx.log("🧠 Step 1: Decomposing master goal into specialized engineering roles...");

    // Ask Freebuff's Thinker to evaluate the broad prompt and assign domain-expert roles
const strategicPlan = await ctx.callAgent('Thinker', {
  prompt: `Analyze this request: "${massiveUserInput}".
           Decompose it into as many completely independent specialized roles as necessary.
           
           Format your output strictly as a JSON array matching this exact schema:
           {
             "subagents": [
               {
                 "name": "UniqueTitleBasedOnTask",
                 "role": "Detailed description of the specific responsibilities for this role",
                 "focusFiles": ["paths/to/targeted/files/here.ts"]
               }
             ]
           }`,
  responseFormat: 'json'
});

    const plan = JSON.parse(strategicPlan.text);
    ctx.log(`🎯 Generated ${plan.subagents.length} specialized domain subagents.`);

    // Step 2: Spin off the dynamic role-based subagents in parallel
    const agentTasks = plan.subagents.map(async (agentSpec) => {
      ctx.log(`🚀 Spawning Dynamic Role Subagent: [${agentSpec.name}]`);

      // Spawn a dynamic agent container that inherits Freebuff's core functional engines
      return ctx.spawnAgent({
        name: agentSpec.name,
        role: agentSpec.role,
        isolated: true,
        // System prompt instructs the custom agent how to use the built-in primitives
        systemPrompt: `
          You are the specialized dynamic agent: [${agentSpec.name}]. Your role is: ${agentSpec.role}.
          You must execute your goals by coordinating Freebuff's internal primitives.
          
          Your execution protocol:
          1. Call 'FileExplorer' to scan your assigned scope: ${JSON.stringify(agentSpec.focusFiles)}.
          2. Call 'Planner' to design the file structural updates.
          3. Call 'Implementation' to write the code.
          4. Call 'Testing' to verify the edits pass local terminal compilation checks.
        `,
        // Grant the dynamic child permission to call Freebuff's native toolchain
        allowedAgents: ['FileExplorer', 'Planner', 'Implementation', 'Testing', 'CodeReview']
      });
    });

    // Step 3: Run all specialized domains concurrently in the background
    ctx.log("⚡ Executing specialized swarms concurrently in Codespaces...");
    const results = await Promise.all(agentTasks);

    // Step 4: Final validation and synchronization
    ctx.log("🗙 Swarms completed. Running final system compilation and review...");
    
    const finalReview = await ctx.callAgent('CodeReview', {
      prompt: "Review the global diffs generated by the specialized subagents to guarantee zero schema or endpoint mismatches."
    });

    await ctx.callAgent('Documentation', {
      prompt: "Update project readmes and log changes executed across all modules."
    });

    return `🏆 Hierarchical multi-agent delivery successful!\n\nReview Status: ${finalReview.text}`;
  }
});
