import React from 'react';
import {Audio} from '@remotion/media';
import {AbsoluteFill,Sequence,staticFile} from 'remotion';
import {C} from './shared';
import {Hook} from './Hook';
import {Entry} from './Entry';
import {Dialects} from './Dialects';
import {Verbs} from './Verbs';
import {Practice} from './Practice';
import {Contribution} from './Contribution';
import {Finale} from './Finale';
export const BikolArchive30V4:React.FC=()=> <AbsoluteFill style={{background:C.night}}><Audio src={staticFile('soundtrack.wav')} volume={0.8}/><Sequence from={0} durationInFrames={118}><Hook/></Sequence><Sequence from={95} durationInFrames={158}><Entry/></Sequence><Sequence from={225} durationInFrames={155}><Dialects/></Sequence><Sequence from={355} durationInFrames={170}><Verbs/></Sequence><Sequence from={500} durationInFrames={155}><Practice/></Sequence><Sequence from={630} durationInFrames={170}><Contribution/></Sequence><Sequence from={760} durationInFrames={140}><Finale/></Sequence></AbsoluteFill>;
